python_quotes = ["The joy of coding Python should be in seeing short, concise, readable classes that express a lot of action in a small amount of clear code -- not in reams of trivial code that bores the reader to death. - Guido van Rossum",
                 "My favorite language for maintainability is Python. It has simple, clean syntax, object encapsulation, good library support, and optional named parameters. - Bram Cohen",
                 "As it seems to me, in Perl you have to be an expert to correctly make a nested data structure like, say, a list of hashes of instances. In Python, you have to be an idiot not to be able to do it, because you just write it down. - Peter Norvig",
                 "In many ways, it's a dull language, borrowing solid old concepts from many other languages & styles: boring syntax, unsurprising semantics, few automatic coercions, etc etc. But that's one of the things I like about Python. - Tim Peters",
                 "Everyone knows that any scripting language shootout that doesn't show Python as the best language is faulty by design. - Max M",
                 "Every sufficiently advanced LISP application will eventually reimplement Python. - Hodgson's Law",
                 "The  canonical, 'Python is a great first language', elicited, 'Python is a great last language!' - Noah Spurrier",
                 "Python is the most powerful language you can still read. - Paul Dubois",
                 "Python tricks is a tough one, cuz the language is so clean. E.g., C makes an art of confusing pointers with arrays and strings, which leads to lotsa neat pointer tricks; APL mistakes everything for an array, leading to neat one-liners; and Perl confuses everything period, making each line a joyous adventure ;-) - Tim Peters",
                 "Python is a truly wonderful language. When somebody comes up with a good idea it takes about 1 minute and five lines to program something that almost does what you want. Then it takes only an hour to extend the script to 300 lines, after which it still does almost what you want. - Jack Jansen",
                 "Python is an experiment in how much freedom programmers need. Too much freedom and nobody can read another's code; too little and expressiveness is endangered. - Guido van Rossum",
                 "I suggested holding a 'Python Object Oriented Programming Seminar', but the acronym was unpopular. - Joseph Strout",
                 "PYTHON = (P)rogrammers (Y)earning (T)o (H)omestead (O)ur (N)oosphere. - Sean McGrath",
                 "Abstraction is one of those notions that Python tosses out the window, yet expresses very well.- Gordon McMillan",
                 "Surprisingly enough, Python has taught me more about Lisp than Lisp ever did ;-). - Glyph Lefkowitz"]
